#ifdef __PORT__

/*
 * Strong host fallbacks for the remaining low hex-coded asm-only SFX symbols.
 */
#define PORT_STRONG_SFX_HEXLOW_DATA(name) unsigned char name[4096]

PORT_STRONG_SFX_HEXLOW_DATA(sfx6B);
PORT_STRONG_SFX_HEXLOW_DATA(sfx7E);
PORT_STRONG_SFX_HEXLOW_DATA(sfx80);
PORT_STRONG_SFX_HEXLOW_DATA(sfx81);
PORT_STRONG_SFX_HEXLOW_DATA(sfx82);
PORT_STRONG_SFX_HEXLOW_DATA(sfx86);
PORT_STRONG_SFX_HEXLOW_DATA(sfx88);
PORT_STRONG_SFX_HEXLOW_DATA(sfx9B);
PORT_STRONG_SFX_HEXLOW_DATA(sfx9C);
PORT_STRONG_SFX_HEXLOW_DATA(sfx9D);
PORT_STRONG_SFX_HEXLOW_DATA(sfx9E);
PORT_STRONG_SFX_HEXLOW_DATA(sfx9F);
PORT_STRONG_SFX_HEXLOW_DATA(sfxA0);
PORT_STRONG_SFX_HEXLOW_DATA(sfxA8);
PORT_STRONG_SFX_HEXLOW_DATA(sfxA9);
PORT_STRONG_SFX_HEXLOW_DATA(sfxAA);
PORT_STRONG_SFX_HEXLOW_DATA(sfxAC);
PORT_STRONG_SFX_HEXLOW_DATA(sfxAE);
PORT_STRONG_SFX_HEXLOW_DATA(sfxAF);
PORT_STRONG_SFX_HEXLOW_DATA(sfxB0);
PORT_STRONG_SFX_HEXLOW_DATA(sfxB5);
PORT_STRONG_SFX_HEXLOW_DATA(sfxB6);
PORT_STRONG_SFX_HEXLOW_DATA(sfxB7);
PORT_STRONG_SFX_HEXLOW_DATA(sfxB8);
PORT_STRONG_SFX_HEXLOW_DATA(sfxB9);
PORT_STRONG_SFX_HEXLOW_DATA(sfxBA);
PORT_STRONG_SFX_HEXLOW_DATA(sfxBB);
PORT_STRONG_SFX_HEXLOW_DATA(sfxBC);
PORT_STRONG_SFX_HEXLOW_DATA(sfxBD);
PORT_STRONG_SFX_HEXLOW_DATA(sfxBE);
PORT_STRONG_SFX_HEXLOW_DATA(sfxBF);
PORT_STRONG_SFX_HEXLOW_DATA(sfxC0);
PORT_STRONG_SFX_HEXLOW_DATA(sfxC1);
PORT_STRONG_SFX_HEXLOW_DATA(sfxC2);
PORT_STRONG_SFX_HEXLOW_DATA(sfxC3);
PORT_STRONG_SFX_HEXLOW_DATA(sfxC4);
PORT_STRONG_SFX_HEXLOW_DATA(sfxC5);
PORT_STRONG_SFX_HEXLOW_DATA(sfxC6);
PORT_STRONG_SFX_HEXLOW_DATA(sfxC7);
PORT_STRONG_SFX_HEXLOW_DATA(sfxC8);
PORT_STRONG_SFX_HEXLOW_DATA(sfxC9);
PORT_STRONG_SFX_HEXLOW_DATA(sfxCA);
PORT_STRONG_SFX_HEXLOW_DATA(sfxCB);
PORT_STRONG_SFX_HEXLOW_DATA(sfxCF);
PORT_STRONG_SFX_HEXLOW_DATA(sfxD0);
PORT_STRONG_SFX_HEXLOW_DATA(sfxD9);
PORT_STRONG_SFX_HEXLOW_DATA(sfxDA);
PORT_STRONG_SFX_HEXLOW_DATA(sfxE3);
PORT_STRONG_SFX_HEXLOW_DATA(sfxE4);
PORT_STRONG_SFX_HEXLOW_DATA(sfxEA);
PORT_STRONG_SFX_HEXLOW_DATA(sfxEB);
PORT_STRONG_SFX_HEXLOW_DATA(sfxEC);
PORT_STRONG_SFX_HEXLOW_DATA(sfxED);
PORT_STRONG_SFX_HEXLOW_DATA(sfxEE);
PORT_STRONG_SFX_HEXLOW_DATA(sfxEF);
PORT_STRONG_SFX_HEXLOW_DATA(sfxF0);
PORT_STRONG_SFX_HEXLOW_DATA(sfxF1);
PORT_STRONG_SFX_HEXLOW_DATA(sfxF2);
PORT_STRONG_SFX_HEXLOW_DATA(sfxF3);
PORT_STRONG_SFX_HEXLOW_DATA(sfxF5);
PORT_STRONG_SFX_HEXLOW_DATA(sfxF8);
PORT_STRONG_SFX_HEXLOW_DATA(sfxFA);
PORT_STRONG_SFX_HEXLOW_DATA(sfxFB);
PORT_STRONG_SFX_HEXLOW_DATA(sfxFC);
PORT_STRONG_SFX_HEXLOW_DATA(sfxFF);

#endif /* __PORT__ */
