import groovy.json.JsonOutput
import groovy.json.JsonSlurper

plugins {
    id("com.android.application")
}

// android/ sits one level under the repository root.
val repoRoot: File = rootProject.projectDir.parentFile

fun stringProp(name: String, fallback: String): String =
    (project.findProperty(name) as String?)?.trim()?.takeIf { it.isNotEmpty() } ?: fallback

val viewWidth = stringProp("tmc.viewWidth", "320")
val viewHeight = stringProp("tmc.viewHeight", "240")

val baseRomPath = stringProp("tmc.baserom", "baserom.gba")
val baseRom: File = File(baseRomPath).let { if (it.isAbsolute) it else File(repoRoot, baseRomPath) }

val assetExtractor: File = File(repoRoot, "tools/bin/asset_extractor")

// Optional, hand-authored, and not generated by anything: the app's private
// files directory is awkward to reach on a device, so this is how a config.json
// (input bindings above all) gets onto one. Absent by default.
val extraConfig: File = File(projectDir, "config.json")

// Everything baked into the APK lives under a single `gamedata/` directory.
// The activity mirrors that one subtree into the app's files dir, which is
// where port_main.c chdir()s to -- so the on-device layout ends up identical
// to a desktop install (baserom.gba next to assets/).
val stageRoot: File = layout.buildDirectory.dir("gamedata-root").get().asFile
val stageDir = File(stageRoot, "gamedata")

// ---------------------------------------------------------------------------
// Build-time asset extraction
// ---------------------------------------------------------------------------
// The same headless extractor the desktop build ships, run against the ROM
// here rather than on the device. Its output carries a fingerprint the engine
// checks on launch (AssetExtractorApi::RuntimeUpToDate); when that matches,
// the first launch skips extraction entirely, which is the whole point of
// baking the tree in. TmcActivity repairs the fingerprint after staging --
// see the comment there for why it cannot survive the trip as written.

val buildAssetExtractor by tasks.registering {
    description = "Builds tools/bin/asset_extractor with xmake."
    inputs.files(
        File(repoRoot, "xmake.lua"),
        fileTree(File(repoRoot, "tools/src/assets_extractor")),
    )
    outputs.file(assetExtractor)
    doLast {
        // Gradle launched from a desktop environment does not always inherit
        // the user's PATH additions, and xmake is commonly a ~/.local install.
        val candidates = listOf(
            "xmake",
            File(System.getProperty("user.home"), ".local/bin/xmake").path,
        )
        val xmake = candidates.firstOrNull { candidate ->
            candidate == "xmake" || File(candidate).canExecute()
        } ?: error("xmake not found; needed to build tools/bin/asset_extractor")

        providers.exec {
            workingDir = repoRoot
            // `xmake build <target>` reuses the existing configuration. It must
            // never be an `xmake f`: that would drop the viewport size the
            // maintainer has configured for their desktop build.
            commandLine(xmake, "build", "asset_extractor")
        }.result.get().assertNormalExitValue()
    }
}

val stageGameData by tasks.registering {
    description = "Extracts the game assets from the ROM and stages them for packaging."
    dependsOn(buildAssetExtractor)
    // inputs.files, not inputs.file: a missing ROM must reach the explanatory
    // error below rather than dying in Gradle's input snapshotting.
    inputs.files(baseRom, assetExtractor, extraConfig)
    outputs.dir(stageRoot)

    doLast {
        if (!baseRom.isFile) {
            error(
                "ROM not found at ${baseRom.absolutePath}.\n" +
                    "The engine treats a missing ROM as fatal even with every asset " +
                    "extracted, so it is baked into the APK. Point tmc.baserom at yours."
            )
        }

        stageDir.deleteRecursively()
        stageDir.mkdirs()

        // The extractor resolves its output root from /proc/self/exe, so it has
        // to run from a copy sitting in the directory we want written.
        val extractorCopy = File(stageDir, "asset_extractor")
        assetExtractor.copyTo(extractorCopy, overwrite = true)
        extractorCopy.setExecutable(true)
        baseRom.copyTo(File(stageDir, "baserom.gba"), overwrite = true)

        providers.exec {
            workingDir = stageDir
            // --pak matches the engine's default (Port_LooseAssetsRequested is
            // off), and the two must agree or the freshness check rejects the
            // tree and re-extracts on the device. --runtime-only skips the
            // editable assets_src/ tree, which nothing on device reads.
            commandLine(extractorCopy.absolutePath, "--runtime-only", "--pak")
        }.result.get().assertNormalExitValue()

        extractorCopy.delete()

        val assetsDir = File(stageDir, "assets")
        if (!assetsDir.isDirectory) {
            error("asset extraction produced no assets/ directory in $stageDir")
        }

        // The extractor drops sounds.json beside assets/ rather than in it.
        // Inside is where the audio backend's cwd-relative probe looks
        // (port_m4a_backend.cpp), and cwd is all we get on Android.
        val sounds = File(stageDir, "sounds.json")
        if (sounds.isFile) {
            sounds.copyTo(File(assetsDir, "sounds.json"), overwrite = true)
            sounds.delete()
        }

        // Two problems with the state file, both fixed here:
        //   - aapt2 drops assets whose name begins with a dot, so it is
        //     packaged undotted and TmcActivity restores the name.
        //   - its `files` array is 2 MB of host-side bookkeeping for the
        //     editable tree, which is never built on device.
        val state = File(assetsDir, ".asset_build_state.json")
        if (state.isFile) {
            @Suppress("UNCHECKED_CAST")
            val parsed = JsonSlurper().parse(state) as MutableMap<String, Any?>
            parsed.remove("files")
            File(assetsDir, "asset_build_state.json").writeText(JsonOutput.toJson(parsed))
            state.delete()
        } else {
            error("asset extraction wrote no .asset_build_state.json")
        }

        // Lands next to the ROM, which is the cwd the engine reads it from.
        if (extraConfig.isFile) {
            extraConfig.copyTo(File(stageDir, "config.json"), overwrite = true)
            logger.lifecycle("staged app/config.json into the APK")
        }
    }
}

android {
    namespace = "org.tmc.port"
    compileSdk = 36
    ndkVersion = "27.3.13750724"

    defaultConfig {
        applicationId = "org.tmc.port"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "0.2.0-pre"

        ndk {
            // arm64 only, as asked. Adding an ABI here also multiplies the
            // native build time by the number of ABIs.
            abiFilters += "arm64-v8a"
        }

        externalNativeBuild {
            cmake {
                arguments += listOf(
                    "-DANDROID_STL=c++_shared",
                    "-DTMC_VIEW_W=$viewWidth",
                    "-DTMC_VIEW_H=$viewHeight",
                )
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
        }
    }

    sourceSets["main"].apply {
        // SDL's Java glue is compiled straight out of the submodule so it can
        // never drift from the libSDL3.so built next to it.
        java.srcDir(File(repoRoot, "libs/SDL/android-project/app/src/main/java"))
        assets.srcDir(stageRoot)
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    lint {
        abortOnError = false
    }
}

// The staged tree is produced by a task, so the asset merge has to wait for it.
tasks.matching { it.name.startsWith("merge") && it.name.endsWith("Assets") }
    .configureEach { dependsOn(stageGameData) }
